parse old and new timestamp formats
luka1199/geo-heatmap pull request #55
Opened 2022-03-16 00:18 UTC by dhimmel

Was getting an error:

```
ValueError: invalid literal for int() with base 10: '2012-07-30T17:47:01.687Z'
```

I think the updated location data now uses RFC 3339 formatted strings.

## references

- https://discuss.python.org/t/parse-z-timezone-suffix-in-datetime/2220

2022-04-04 10:30 UTC, jablpiotrek approved these changes

2022-04-04 11:12 UTC, luka1199 requested changes

2022-04-04 11:12 UTC, luka1199 commented on utils.py
> +def parse_timestamp(timestamp: str) -> datetime:
Can you change this to camel case for consistency?

2022-04-05 08:55 UTC, jablpiotrek approved these changes

2022-04-07 14:18 UTC, merged